# -*- coding: utf-8 -*-
"""Monte_Carlo_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxaZFcWGk8BNNAoUMl8TtHvVLdSWq8Ln
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import statsmodels.api as sm
from statsmodels.discrete.discrete_model import Probit
import pandas as pd

data_path = "Armour_UHMWPE.xlsx"
df = pd.read_excel(data_path,sheet_name='Panel 1')

velocities = df["Velocity(m/s)"].to_numpy(dtype=float)
outcomes   = df["Outcome"].to_numpy(dtype=int)

X = sm.add_constant(velocities)
model = Probit(outcomes, X)
result = model.fit(disp=False)

a, b = result.params
cov = result.cov_params()

V10 = (norm.ppf(0.1)- a)/ b
V50 = - a/ b
V99 = (norm.ppf(0.99)- a)/ b

def gradient(zp, a, b, cov):
    dVa = -1 / b
    dVb = -(zp - a) / (b**2)
    grad = np.array([dVa, dVb])
    return grad.dot(cov).dot(grad.T)

std_V10 = np.sqrt(gradient(norm.ppf(0.1), a, b, cov))
std_V50 = np.sqrt(gradient(0, a, b, cov))
std_V99 = np.sqrt(gradient(norm.ppf(0.99), a, b, cov))

#print(result.summary())
print("\n Ballistic Limits with Uncertainty ")
print(f"α = {a:.4f}, β = {b:.6f}")
print(f"V10 = {V10:.2f} ± {std_V10:.2f} m/s")
print(f"V50 = {V50:.2f} ± {std_V50:.2f} m/s")
#print(f"V99 = {V99:.2f} ± {std_V99:.2f} m/s")
#print(f"Transition width (V99–V10) = {V99 - V10:.2f} m/s")

v_grid = np.linspace(500, 1500, 100)
X_grid = sm.add_constant(v_grid)
p_fit = result.predict(X_grid)

plt.figure(figsize=(7,5))
plt.plot(v_grid, p_fit, color="black", linewidth=2, label="Probit fit")
#plt.axvline(V10, color="green", linestyle="--", label="V10")
plt.axvline(V50, color="orange", linestyle="--", label="V50")
#plt.axvline(V99, color="purple", linestyle="--", label="V99")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Probability of perforation")
plt.title("Probit Fit (Statsmodels): Probability of Perforation vs Velocity")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.ylim(-0.05, 1.05)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm
import statsmodels.api as sm
from statsmodels.discrete.discrete_model import Probit

data_path = "Armour_UHMWPE.xlsx"

df = pd.read_excel(data_path,sheet_name='Panel 1')

velocities = df["Velocity(m/s)"].to_numpy(dtype=float)
outcomes   = df["Outcome"].to_numpy(dtype=int)

X = sm.add_constant(velocities)
model = Probit(outcomes, X)
result = model.fit(disp=False)

a, b = result.params
cov = result.cov_params()

print("\n=== Probit fit on REAL data ===")
print(f"alpha = {a:.4f}")
print(f"beta  = {b:.6f}")


def ballistic_limit(z):
    return (z - a) / b

V10 = ballistic_limit(norm.ppf(0.1))
V50 = ballistic_limit(0.0)
V90 = ballistic_limit(norm.ppf(0.9))

def delta_var(z):
    dVa = -1.0 / b
    dVb = -(z - a) / (b**2)
    grad = np.array([dVa, dVb])
    return grad @ cov @ grad.T

std_V10 = np.sqrt(delta_var(norm.ppf(0.1)))
std_V50 = np.sqrt(delta_var(0.0))
std_V90 = np.sqrt(delta_var(norm.ppf(0.9)))

print("\n--- Ballistic limits (REAL) ---")
print(f"V10 = {V10:.2f} ± {std_V10:.2f}")
print(f"V50 = {V50:.2f} ± {std_V50:.2f}")
print(f"V90 = {V90:.2f} ± {std_V90:.2f}")
print(f"Transition width (V90–V10) = {V90 - V10:.2f}")

n_synth = 300

v_min = velocities.min() - 50
v_max = velocities.max() + 150

v_syn = np.linspace(v_min, v_max, n_synth)

X_syn = sm.add_constant(v_syn)
p_syn = result.predict(X_syn)

y_syn = np.random.binomial(1, p_syn)

synthetic_df = pd.DataFrame({
    "velocity": v_syn,
    "outcome": y_syn
})
with pd.ExcelWriter("Enhanced dataset.xlsx", engine='openpyxl', mode='a', if_sheet_exists='new') as writer:
  synthetic_df.to_excel(writer,index=False, sheet_name='UHMWPE')

print("\nSynthetic dataset generated:")
print(synthetic_df.groupby("outcome").size())
X2 = sm.add_constant(synthetic_df["velocity"])
model2 = Probit(synthetic_df["outcome"], X2)
res2 = model2.fit(disp=False)

a2, b2 = res2.params

V50_syn = -a2 / b2

print("\n=== Probit fit on SYNTHETIC data ===")
print(f"alpha = {a2:.4f}")
print(f"beta  = {b2:.6f}")
print(f"V50 (synthetic) = {V50_syn:.2f}")

v_grid = np.linspace(v_min, v_max, 400)
X_grid = sm.add_constant(v_grid)

p_real = result.predict(X_grid)
p_syn_fit = res2.predict(X_grid)

plt.figure(figsize=(8,6))

plt.plot(v_grid, p_real, "k", lw=2, label="Probit (real data)")
plt.plot(v_grid, p_syn_fit, "r--", lw=2, label="Probit (synthetic data)")

plt.scatter(
    velocities[outcomes == 1],
    outcomes[outcomes == 1],
    color="red", s=35, label="Perforation (real)", zorder=3
)

plt.scatter(
    velocities[outcomes == 0],
    outcomes[outcomes == 0],
    color="blue", s=35, label="No perforation (real)", zorder=3
)
plt.axvline(V10, color="green", linestyle="--", label="V10 (real)")
plt.axvline(V50, color="orange", linestyle="--", label="V50 (real)")
plt.axvline(V90, color="purple", linestyle="--", label="V90 (real)")

plt.xlabel("Impact velocity")
plt.ylabel("Probability of perforation")
plt.title("Ballistic S-curve (Probit)\nReal vs Synthetic Monte-Carlo Data")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.ylim(-0.05, 1.05)

plt.tight_layout()
plt.show()